config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root  'home#index'
  get 'sessions/new'
  resources :users
  resources :rentals
  resources :items
  
  get     'home/index'
  get     '/signup',      to: 'users#new'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  get     '/logout',      to: 'sessions#destroy'
  get     '/items',       to: 'items#index'
  get     '/items/:id',   to: 'items#show'
  post    '/items/new',   to: 'items#new'
  post    '/rentals/approve_rental', to: 'rentals#approve_rental'
  post    '/rentals/deny_rental', to: 'rentals#deny_rental'
  post    '/rentals/buyer_checkin_confirm', to: 'rentals#buyer_checkin_confirm'
  post    '/rentals/seller_checkin_confirm', to: 'rentals#seller_checkin_confirm'
  post    '/rentals/buyer_rental_rating', to: 'rentals#buyer_rental_rating'
  post    '/rentals/seller_rental_rating', to: 'rentals#seller_rental_rating'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    geocoded_by :address
    after_validation :geocode
    before_save { self.email = email.downcase }
    has_many :items
    has_many :rentals
    has_many :comments
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    #validates :username, presence: true, length: { maximum: 50 },
    #                uniqueness: {case_sensitive: false }
    validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with:  VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    def address
        [street, city, zip, state].compact.join(", ") 
    end
    
    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    
    if !@user
      redirect_to root_path
    else
      @user = User.find(params[:id])
      @rentals = @user.rentals.where(buyer_checkin_confirm: false).or(Rental.where(seller_checkin_confirm: false))
      @pending_items = Rental.where(item_id: @user.items).where(approval: false)
      puts "RENTALS: " + @rentals.count.to_s
      puts "PENDING: " + @pending_items.count.to_s
      @rental_buyer_history = Rental.where(user_id: params[:id]).where(buyer_checkin_confirm: true).where(seller_checkin_confirm: true)
      @rental_seller_history = Rental.where(item_id: @user.items).where(buyer_checkin_confirm: true).where(seller_checkin_confirm: true)
      #@rental_history = @rental_buyer_history + @rental_seller_history
      puts "BUYER HISTORY: " + @rental_buyer_history.count.to_s
      puts @rental_buyer_history
      puts "SELLER HISTORY: " + @rental_seller_history.count.to_s
      puts @rental_seller_history
      #@ip_addr = request.env[‘REMOTE_ADDR’]
      
      @comments = Comment.where(commented_id: params[:id])
      
      @rating_sum = 0
      @rating_count = 0
      
      if @rental_buyer_history.count > 0
        @rental_buyer_history.each do |brental|
          if brental.seller_rating
            @rating_sum = @rating_sum + brental.seller_rating
            @rating_count = @rating_count + 1
          end
        end
      end
      
      if @rental_seller_history.count > 0
        @rental_seller_history.each do |srental|
          if srental.buyer_rating
            @rating_sum = @rating_sum + srental.buyer_rating
            @rating_count = @rating_count + 1
          end
        end
      end
      
      puts "RATING SUM: " + @rating_sum.to_s
      puts "RATING COUNT: " + @rating_count.to_s
      
      if @rating_count > 0
        @rating = (@rating_sum / @rating_count).ceil
      else
        @rating = 0
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
    @user.admin = false
    @user.status = false


      if @user.save
        redirect_to action: "index", controller: "home"
        #format.json { render :show, status: :created, location: @user }
      else
        #format.html { render :new }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
        redirect_to action: "index", controller: "home"
      end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:fname, :lname, :email, :username, :password, :status, :admin, :street, :city, :state, :zip, :latitude, :longitude)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_buyer_history.html.erb
<table class="table table-striped">
    <thead class="thead-grey text-center">
        <tr>
          <th scope="col">Item Name</th>
          <th scope="col">Seller</th>
          <th scope="col">Rental Start Date</th>
          <th scope="col">Rental End Date</th>
          <th scope="col">Price</th>
          <th scope="col">Rating</th>
        </tr>
    </thead>
    <tbody>
        <% if buyer_history.count > 0 %>
            <% buyer_history.each do |rental| %>
                <tr class="text-center">
                  <th scope="row"><%= rental.item.name %></th>
                  <td><%= rental.item.user.username %></td>
                  <td><%= rental.rental_start_date.strftime("%B %d, %Y") %></td>
                  <td><%= rental.rental_end_date.strftime("%B %d, %Y") %></td>
                  <td><%= number_to_currency(rental.total_price) %></td>
                  <td>
                      <% if rental.buyer_rating %>
                          <%= render 'flat_rating', rating: rental.buyer_rating %>
                      <% else %>
                          <%= render 'buyer_rating', rental: rental %>
                      <% end %>
                  </td>
                </tr>
            <% end %>
        <% else %>
            <tr class="text-center">
                <td colspan="6">
                    You do not have any rentals to show in your history.
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/_buyer_rating.html.erb
<%= form_tag(rentals_buyer_rental_rating_path(:rental_id => rental.id), :id => rental.id, remote: true, authenticity_token: true, method: "post") do %>
  <div class="rating ml-auto mr-auto">
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="5" title="5 stars"> 5
    </label>
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="4" title="4 stars"> 4
    </label>
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="3" title="3 stars"> 3
    </label>
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="2" title="2 stars"> 2
    </label>
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="1" title="1 star"> 1
    </label>
  </div>
<% end %>

app/views/users/_flat_rating.html.erb
<span class="profile-rating">
    <% orating = 5 - rating %>
    <% (1..rating).each do |i| %>
      <%= fa_icon('star') %>   
    <% end %>
    <% (1..orating).each do |i| %>
      <%= fa_icon('star-o') %>   
    <% end %>
</span>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :lname %>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation %>
  </div>
  
  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>
  
  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
  
  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>
  
  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_pending.html.erb
<table class="table table-striped">
    <thead class="thead-grey text-center">
        <tr>
          <th scope="col">Item Name</th>
          <th scope="col">Buyer</th>
          <th scope="col">Rental Start Date</th>
          <th scope="col">Rental End Date</th>
          <th scope="col">Price</th>
          <th scope="col">Comment</th>
          <th scope="col">Assist</th>
          <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% if pending_items.count > 0 %>
            <% pending_items.each do |rental| %>
                <tr class="text-center">
                  <th scope="row"><%= rental.item.name %></th>
                  <td><%= rental.user.username %></td>
                  <td><%= rental.rental_start_date.strftime("%B %d, %Y") %></td>
                  <td><%= rental.rental_end_date.strftime("%B %d, %Y") %></td>
                  <td><%= number_to_currency(rental.total_price) %></td>
                  <td>
                      <%= truncate(rental.comment, :length => 30) %>
                  </td>
                  <td><%= rental.assistance_reason %></td>
                  <td>
                      <div class="btn-group" role="group">
                      <%= button_to rentals_approve_rental_path(:rental_id => rental.id), remote: true, :class => "btn btn-info", method: :post do %>
                          <%= fa_icon("check-circle") %>
                      <% end %>
                      <%= button_to rentals_deny_rental_path(:rental_id => rental.id), remote: true, :class => "btn btn-info ml-1", method: :post do %>
                          <%= fa_icon("times-circle") %>
                      <% end %>
                     </div>
                  </td>
                </tr>
            <% end %>
        <% else %>
            <tr class="text-center">
                <td colspan="6">
                    You do not have any rentals to show in your history.
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/_seller_history.html.erb
<table class="table table-striped">
    <thead class="thead-grey text-center">
        <tr>
          <th scope="col">Item Name</th>
          <th scope="col">Buyer</th>
          <th scope="col">Rental Start Date</th>
          <th scope="col">Rental End Date</th>
          <th scope="col">Price</th>
          <th scope="col">Rating</th>
        </tr>
    </thead>
    <tbody>
        <% if seller_history.count > 0 %>
            <% seller_history.each do |rental| %>
                <tr class="text-center">
                  <th scope="row"><%= rental.item.name %></th>
                  <td><%= rental.user.username %></td>
                  <td><%= rental.rental_start_date.strftime("%B %d, %Y") %></td>
                  <td><%= rental.rental_end_date.strftime("%B %d, %Y") %></td>
                  <td><%= number_to_currency(rental.total_price) %></td>
                  <td>
                      <% if rental.seller_rating %>
                          <%= render 'flat_rating', rating: rental.seller_rating %>
                      <% else %>
                          <%= render 'seller_rating', rental: rental %>
                      <% end %>
                      
                  </td>
                </tr>
            <% end %>
        <% else %>
            <tr class="text-center">
                <td colspan="6">
                    You do not have any rentals to show in your history.
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/_seller_rating.html.erb
<%= form_tag(rentals_seller_rental_rating_path(:rental_id => rental.id), :id => rental.id, remote: true, authenticity_token: true, method: "post") do %>
  <div class="rating ml-auto mr-auto">
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="5" title="5 stars"> 5
    </label>
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="4" title="4 stars"> 4
    </label>
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="3" title="3 stars"> 3
    </label>
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="2" title="2 stars"> 2
    </label>
    <label>
      <input class="bhr <%= rental.id %>" type="radio" name="rating" value="1" title="1 star"> 1
    </label>
  </div>
<% end %>

app/views/users/_signup.html.erb
 <%= form_with(model: user, url: users_path, remote: true) do |form| %>
 
  <div class="form-group row">
    <%= form.label "First Name:", :class => "col-4 col-form-label" %>
    <div class="col-8">
          <%= form.text_field :fname, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label "Last Name:", :class => "col-4 col-form-label" %>
    <div class="col-8">
          <%= form.text_field :lname, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label "Email:", :class => "col-4 col-form-label" %>
    <div class="col-8">
          <%= form.email_field :email, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label "Password:", :class => "col-4 col-form-label" %>
    <div class="col-8">
          <%= form.password_field :password, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label "Password Confirm:", :class => "col-4 col-form-label" %>
    <div class="col-8">
          <%= form.password_field :password_confirmation, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label "Street:", :class => "col-4 col-form-label" %>
    <div class="col-8">
          <%= form.text_field :street, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label "City:", :class => "col-4 col-form-label" %>
    <div class="col-8">
          <%= form.text_field :city, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label "State:", :class => "col-4 col-form-label" %>
    <div class="col-8">
          <%= form.text_field :state, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label "Zip:", :class => "col-4 col-form-label" %>
    <div class="col-8">
          <%= form.text_field :zip, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="actions">
      <%= form.submit "Sign Up", :class => "btn btn-info post-item-btn" %>
  </div>
<%end%>

app/views/users/_user_card.html.erb
<div class="row">
      <div class="col bg-light">
          <%= image_tag("default_avatar.jpg", :class => "profile-picture mx-auto d-block") %>
      </div>
      <div class="col bg-light nav-buffer text-center">
        <span class="profile-user-name mt-3"><%= user.fname + " " + user.lname %></span></br>
          <%= render 'flat_rating', rating: @rating %>
          (<%= @rating_count %>)</br>
        <strong>Joined:</strong> <%= user.created_at.strftime("%B %Y") %></br>
        <strong>Location:</strong> <%= user.city + ", " + user.state %></br>
        <div class="verified-container d-flex justify-content-center mt-3">
          <div class="verified-item text-center mx-auto float-left">
            <%= fa_icon('facebook-square 3x') %>Facebook Verified
          </div>
          <div class="verified-item text-center mx-auto float-left">
            <%= fa_icon('twitter-square 3x') %>Twitter Verified
          </div>
          <div class="verified-item text-center mx-auto float-left">
            <%= fa_icon('envelope 3x') %>Email Verified
          </div>
          <div class="verified-item text-center mx-auto float-left">
            <%= fa_icon('money 3x') %>Verified for Payments
          </div>
        </div>
        
      </div>   
      <div class="col-md-6 bg-light nav-buffer">
        <%= image_tag("http://maps.googleapis.com/maps/api/staticmap?center=#{user.latitude},#{user.longitude}&zoom=15&size=450x200&key=AIzaSyA_x25mqDphJPz0jrC21MWQCICDKqxTCL8", :class => "mx-auto d-block profile-map") %>
      </div> 
    </div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'home/navbar' %>
<h1>Users</h1>
<%= request.remote_ip %>



<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password Digest</th>
      <th>Status</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.status %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= debug(params) if Rails.env.development? %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= stylesheet_link_tag "users", media: "all" %>
<%= render 'home/navbar' %>

  <div class="p-3 p-md-5 text-white bg-info nav-buffer">
    
  </div>
  <div class="album py-3 bg-light">
  <div class="container bg-light">
    <div class="row spacer-20 bg-light"></div>
    <%= render 'user_card', user: @user %>
    <div class="row spacer-20 bg-light"></div>
    <% if current_user %>
      <% if @user.id == current_user.id %>
        <ul class="nav nav-pills mb-3 mt-3" id="pills-tab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="pills-items-tab" data-toggle="pill" href="#pills-items" role="tab" aria-controls="pills-items" aria-selected="true">Your Items</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="pills-pending-tab" data-toggle="pill" href="#pills-pending" role="tab" aria-controls="pills-history" aria-selected="false">Pending Approvals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="pills-history-tab" data-toggle="pill" href="#pills-history" role="tab" aria-controls="pills-history" aria-selected="false">Rental History</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="pills-sales-tab" data-toggle="pill" href="#pills-sales" role="tab" aria-controls="pills-sales" aria-selected="false">Seller History</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="pills-rentals-tab" data-toggle="pill" href="#pills-rentals" role="tab" aria-controls="pills-rentals" aria-selected="false">Current Rentals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="pills-comments-tab" data-toggle="pill" href="#pills-comments" role="tab" aria-controls="pills-comments" aria-selected="false">Comments</a>
          </li>
        </ul>
        <div class="tab-content" id="pills-tabContent">
          <div class="tab-pane fade show active" id="pills-items" role="tabpanel" aria-labelledby="pills-items-tab">
            <div class="row">
              <div class="alert alert-info col-12" role="alert">
                Below are the current items you have in your store.
              </div>
            </div>
            <% if @user.items.count > 0 %>
              <div class="card-group mt-3">
                <% @user.items.each do |item| %>
                  <%= render 'items/item_card', item: item %>
                <% end %>
              </div>
            <% else %>
              <div class="row">
                <p class="ml-3">You have no items available for others to rent. Add one now!</p>
              </div>
            <% end %>
          </div>
          <div class="tab-pane fade" id="pills-pending" role="tabpanel" aria-labelledby="pills-pending-tab">
            <div class="alert alert-info col-12" role="alert">
              Below are the items from your shop that have a rental pending your approval.
            </div>
            <%= render 'pending', pending_items: @pending_items %>
    
          </div>
          <div class="tab-pane fade" id="pills-history" role="tabpanel" aria-labelledby="pills-history-tab">
            <%= render 'buyer_history', buyer_history: @rental_buyer_history %>
          
    
          </div>
          <div class="tab-pane fade" id="pills-sales" role="tabpanel" aria-labelledby="pills-sales-tab">
            <%= render 'seller_history', seller_history: @rental_seller_history %>
          
    
          </div>
          <div class="tab-pane fade" id="pills-rentals" role="tabpanel" aria-labelledby="pills-rentals-tab">
            <div class="row">
              <div class="alert alert-info col-12" role="alert">
                Below are the items you currently have checked out and are renting from other users.
              </div>
            </div>
            <% if @rentals.count > 0 %>
              <div class="card-group mt-3">
                <% @rentals.each do |rental| %>
                  <%= render 'items/item_card', item: rental.item %>
                <% end %>
              </div>
            <% else %>
              <div class="row">
                <p class="ml-3">You currently don't have any items checked out from other users. Add one now!</p>
              </div>
            <% end %>
          </div>
          <div class="tab-pane fade" id="pills-comments" role="tabpanel" aria-labelledby="pills-comments-tab">
            <div class="row">
              
              <div class="col-12">
                <div class="alert alert-info" role="alert">
                  Leave a comment for the user for others to see.
                </div>
                <%= form_with url: comments_path(commented_id: @user.id), :remote => true do |form| %>
                  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="body"></textarea>
                  <button class="btn btn-info float-right mt-3 mb-3" type="submit">Comment</button>
                <% end %>
              </div>
            </div>
            
              <% @comments.each do |comment| %>
                <div class="row">
                  <div class="col-12">
                    <div class="alert alert-secondary" role="alert">
                      <strong><%= comment.user.fname + " " + comment.user.lname %></strong><br>
                      <i><%= comment.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%B %d, %Y") %></i><br><br>
                      <%= comment.body %>
                    </div>
                  </div>
                </div>
              <% end %>
            
    
          </div>
        </div>
      </div>
    <% else %>
      <ul class="nav nav-pills mb-3 mt-3" id="pills-tab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="pills-items-tab" data-toggle="pill" href="#pills-items" role="tab" aria-controls="pills-items" aria-selected="true"><%= @user.fname %>'s Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-comments-tab" data-toggle="pill" href="#pills-comments" role="tab" aria-controls="pills-comments" aria-selected="false">Comments</a>
        </li>
      </ul>
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-items" role="tabpanel" aria-labelledby="pills-items-tab">
          <div class="row">
            <div class="alert alert-info col-12" role="alert">
              Below are the current items you have in your store.
            </div>
          </div>
          <% if @user.items.count > 0 %>
            <div class="card-group mt-3">
              <% @user.items.each do |item| %>
                <%= render 'items/item_card', item: item %>
              <% end %>
            </div>
          <% else %>
            <div class="row">
              <p class="ml-3">You have no items available for others to rent. Add one now!</p>
            </div>
          <% end %>
        </div>
        <div class="tab-pane fade" id="pills-comments" role="tabpanel" aria-labelledby="pills-comments-tab">
            <div class="row">
              
              <div class="col-12">
                <div class="alert alert-info" role="alert">
                  Leave a comment for the user for others to see.
                </div>
                <%= form_with url: comments_path(commented_id: @user.id), :remote => true do |form| %>
                  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="body"></textarea>
                  <button class="btn btn-info float-right mt-3 mb-3" type="submit">Comment</button>
                <% end %>
              </div>
            </div>
            
              <% @comments.each do |comment| %>
                <div class="row">
                  <div class="col-12">
                    <div class="alert alert-secondary" role="alert">
                      <strong><%= comment.user.fname + " " + comment.user.lname %></strong><br>
                      <i><%= comment.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%B %d, %Y") %></i><br><br>
                      <%= comment.body %>
                    </div>
                  </div>
                </div>
              <% end %>
            
    
          </div>
      </div>
    </div>  
    <% end %>
    <% else %>
      <ul class="nav nav-pills mb-3 mt-3" id="pills-tab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="pills-items-tab" data-toggle="pill" href="#pills-items" role="tab" aria-controls="pills-items" aria-selected="true"><%= @user.fname %>'s Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-comments-tab" data-toggle="pill" href="#pills-comments" role="tab" aria-controls="pills-comments" aria-selected="false">Comments</a>
        </li>
      </ul>
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-items" role="tabpanel" aria-labelledby="pills-items-tab">
          <div class="row">
            <div class="alert alert-info col-12" role="alert">
              Below are the current items you have in your store.
            </div>
          </div>
          <% if @user.items.count > 0 %>
            <div class="card-group mt-3">
              <% @user.items.each do |item| %>
                <%= render 'items/item_card', item: item %>
              <% end %>
            </div>
          <% else %>
            <div class="row">
              <p class="ml-3">You have no items available for others to rent. Add one now!</p>
            </div>
          <% end %>
        </div>
        <div class="tab-pane fade" id="pills-comments" role="tabpanel" aria-labelledby="pills-comments-tab">
            <div class="row">
              
              <div class="col-12">
                <div class="alert alert-info" role="alert">
                  Login to leave a comment for the user for others to see.
                </div>
              </div>
            </div>
            
              <% @comments.each do |comment| %>
                <div class="row">
                  <div class="col-12">
                    <div class="alert alert-secondary" role="alert">
                      <strong><%= comment.user.fname + " " + comment.user.lname %></strong><br>
                      <i><%= comment.created_at.strftime("%B %d, %Y") %></i><br><br>
                      <%= comment.body %>
                    </div>
                  </div>
                </div>
              <% end %>
            
    
          </div>
      </div>
    </div>  
    <% end %>
  <div class="row spacer-20 bg-light"></div>
</div>
</div>
<%= render 'home/footer' %>