config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root  'home#index'
  get 'sessions/new'
  resources :users
  resources :rentals
  resources :items
  
  get     'home/index'
  get     '/signup',      to: 'users#new'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  get     '/logout',      to: 'sessions#destroy'
  get     '/items',       to: 'items#index'
  get     '/items/:id',   to: 'items#show'
  post    '/items/new',   to: 'items#new'
  post    '/rentals/approve_rental', to: 'rentals#approve_rental'
  post    '/rentals/deny_rental', to: 'rentals#deny_rental'
  post    '/rentals/buyer_checkin_confirm', to: 'rentals#buyer_checkin_confirm'
  post    '/rentals/seller_checkin_confirm', to: 'rentals#seller_checkin_confirm'
  post    '/rentals/buyer_rental_rating', to: 'rentals#buyer_rental_rating'
  post    '/rentals/seller_rental_rating', to: 'rentals#seller_rental_rating'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rental.rb
class Rental < ApplicationRecord
    belongs_to :item, optional: true
    belongs_to :user, optional: true
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
    
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)
    @item = Item.find(@rental.item_id)
    
    if current_user
      @rental.user_id = current_user.id
      @rental.buyer_checkin_confirm = false
      @rental.seller_checkin_confirm = false
      
      
      
      
      @rental_days = (@rental.rental_end_date - @rental.rental_start_date).to_i/86400
      @rental.total_price = (@rental_days + 1) * @item.price
      @rental.approval = false
      
      puts "RENTAL INFORMATION"
      puts @rental_days
      puts @item.price


        if @rental.save
          #format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
          redirect_to current_user
        else
          format.html { render :new }
          format.json { render json: @rental.errors, status: :unprocessable_entity }
        end
    else
      respond_to do |format|
        flash.now[:danger] = "Please sign in to rent an item."
        format.html { items_path(@item) }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def approve_rental
    puts "HELLO"
    @rental_id = params[:rental_id]
    puts @rental_id
    
    @rental = Rental.find(params[:rental_id])
    
    if current_user
      if current_user.id == @rental.item.user_id
        @rental.approval = true
        @rental.save
      else
        puts "FAIL1"
      end
    else
      puts "FAIL2"
    end
    
    redirect_to current_user
    
  end
  
  def deny_rental
    puts "HELLO"
    @rental_id = params[:rental_id]
    puts @rental_id
    
    @rental = Rental.find(params[:rental_id])
    
    if current_user
      if current_user.id == @rental.item.user_id
        @rental.destroy
      else
        puts "FAIL1"
      end
    else
      puts "FAIL2"
    end
    
    redirect_to current_user
    
  end
  
  def buyer_rental_rating
    puts "LETS GO"
    puts params[:rental_id]
    puts params[:rating]
    
    if current_user
      
      rental = Rental.find(params[:rental_id])
      
      if current_user.id == rental.user_id 
        puts "HELLO1"
        if params[:rating].to_i.between?(1, 5) && !rental.buyer_rating
          puts "HELLO2"
          rental.buyer_rating = params[:rating]
          rental.save
        end
      end
      
      redirect_to current_user
    else
      redirect_to root_path
    end
  end
  
  def seller_rental_rating
    puts "LETS GO"
    puts params[:rental_id]
    puts params[:rating]
    
    
    if current_user
      
      rental = Rental.find(params[:rental_id])
      puts rental.item.user_id
      
      if current_user.id == rental.item.user_id 
        if params[:rating].to_i.between?(1, 5) && !rental.seller_rating
          rental.seller_rating = params[:rating]
          rental.save
        end
      end
      
      redirect_to current_user
    else
      redirect_to root_path
    end
  end
  
  def buyer_checkin_confirm
    
    if current_user
      
      rental = Rental.find(params[:rental_id])
      puts rental.user_id
      
      if current_user.id == rental.user_id
        if rental.buyer_checkin_confirm == false && rental.approval == true
          rental.buyer_checkin_confirm = true
          rental.save
        end
      end
    end
    
    redirect_to current_user
    
  end
  
  def seller_checkin_confirm
    
    if current_user
      
      rental = Rental.find(params[:rental_id])
      puts rental.user_id
      puts rental.id
      
      if current_user.id == rental.item.user_id
        if rental.seller_checkin_confirm == false && rental.approval == true
          rental.seller_checkin_confirm = true
          rental.save
        end
      end
    end
    
    redirect_to current_user
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.permit(:user_id, :item_id, :rental_start_date, :rental_end_date, :buyer_checkin_confirm, :seller_checkin_confirm, :total_price, :assistance, :assistance_reason, :comment)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_with(model: rental, local: true) do |form| %>
  <% if rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.number_field :item_id %>
  </div>

  <div class="field">
    <%= form.label :rental_start_date %>
    <%= form.datetime_select :rental_start_date %>
  </div>

  <div class="field">
    <%= form.label :rental_end_date %>
    <%= form.datetime_select :rental_end_date %>
  </div>

  <div class="field">
    <%= form.label :buyer_checkin_confirm %>
    <%= form.check_box :buyer_checkin_confirm %>
  </div>

  <div class="field">
    <%= form.label :seller_checkin_confirm %>
    <%= form.check_box :seller_checkin_confirm %>
  </div>

  <div class="field">
    <%= form.label :total_price %>
    <%= form.text_field :total_price %>
  </div>

  <div class="field">
    <%= form.label :assistance %>
    <%= form.check_box :assistance %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rentals</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Item</th>
      <th>Rental start date</th>
      <th>Rental end date</th>
      <th>Buyer checkin confirm</th>
      <th>Seller checkin confirm</th>
      <th>Total price</th>
      <th>Assistance</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.user_id %></td>
        <td><%= rental.item_id %></td>
        <td><%= rental.rental_start_date %></td>
        <td><%= rental.rental_end_date %></td>
        <td><%= rental.buyer_checkin_confirm %></td>
        <td><%= rental.seller_checkin_confirm %></td>
        <td><%= rental.total_price %></td>
        <td><%= rental.assistance %></td>
        <td><%= rental.comment %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rental.user_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @rental.item_id %>
</p>

<p>
  <strong>Rental start date:</strong>
  <%= @rental.rental_start_date %>
</p>

<p>
  <strong>Rental end date:</strong>
  <%= @rental.rental_end_date %>
</p>

<p>
  <strong>Buyer checkin confirm:</strong>
  <%= @rental.buyer_checkin_confirm %>
</p>

<p>
  <strong>Seller checkin confirm:</strong>
  <%= @rental.seller_checkin_confirm %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @rental.total_price %>
</p>

<p>
  <strong>Assistance:</strong>
  <%= @rental.assistance %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @rental.comment %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>