config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root  'home#index'
  get 'sessions/new'
  resources :users
  resources :rentals
  resources :items
  
  get     'home/index'
  get     '/signup',      to: 'users#new'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  get     '/logout',      to: 'sessions#destroy'
  get     '/items',       to: 'items#index'
  get     '/items/:id',   to: 'items#show'
  post    '/items/new',   to: 'items#new'
  post    '/rentals/approve_rental', to: 'rentals#approve_rental'
  post    '/rentals/deny_rental', to: 'rentals#deny_rental'
  post    '/rentals/buyer_checkin_confirm', to: 'rentals#buyer_checkin_confirm'
  post    '/rentals/seller_checkin_confirm', to: 'rentals#seller_checkin_confirm'
  post    '/rentals/buyer_rental_rating', to: 'rentals#buyer_rental_rating'
  post    '/rentals/seller_rental_rating', to: 'rentals#seller_rental_rating'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    has_many_attached :images
    has_many :rentals
    belongs_to :user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if params[:search]
      puts "CAME HERE"
      #@items = Item.where("tag like ?", "%#{params[:search]}%")
      @items = Item.where.not(:id => Rental.where(buyer_checkin_confirm: false).or(Rental.where(seller_checkin_confirm: false)).pluck(:item_id)).where("tag like ?", "%#{params[:search]}%")
    else
      puts "ALL"
      @items = Item.all
    end
    
    puts @items.count
  end

  # GET /items/1
  # GET /items/1.json
  def show
    
    if !@item
      redirect_to root_path
    else
    
      @tags = @item.tag.split(',')
      @user_location = request.location.ip
      @distance = @item.user.distance_to(@user_location)
      @similar_items = Item.where("tag like ?", "%#{@tags[0]}%").where.not(user_id: @item.user_id).where.not(:id => Rental.where(buyer_checkin_confirm: false).or(Rental.where(seller_checkin_confirm: false)))
      @user_other_items = @item.user.items.where.not(id: @item.id).where.not(:id => Rental.where(buyer_checkin_confirm: false).or(Rental.where(seller_checkin_confirm: false)))
      
      @rental_buyer_history = Rental.where(user_id: @item.user.id).where(buyer_checkin_confirm: true).where(seller_checkin_confirm: true)
      @rental_seller_history = Rental.where(item_id: @item.user.items).where(buyer_checkin_confirm: true).where(seller_checkin_confirm: true)
      
      @rating_sum = 0
      @rating_count = 0
      
      if @rental_buyer_history.count > 0
        @rental_buyer_history.each do |brental|
          if brental.seller_rating
            @rating_sum = @rating_sum + brental.seller_rating
            @rating_count = @rating_count + 1
          end
        end
      end
      
      if @rental_seller_history.count > 0
        @rental_seller_history.each do |srental|
          if srental.buyer_rating
            @rating_sum = @rating_sum + srental.buyer_rating
            @rating_count = @rating_count + 1
          end
        end
      end
      
      puts "RATING SUM: " + @rating_sum.to_s
      puts "RATING COUNT: " + @rating_count.to_s
      
      if @rating_count > 0
        @rating = (@rating_sum / @rating_count).ceil
      else
        @rating = 0
      end
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    
    if logged_in?
      puts "User logged in, can create item."
      puts current_user.username
      
      @item.user_id = current_user.id
      
      if @item.save
        flash.now[:success] = "Item was successfully added!"
        redirect_to current_user
      else
        respond_to do |format|
          format.html { render :new }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
      
    else
      flash.now[:danger] = "You are not logged in, login to add an item!"
        respond_to do |format|
            format.html { render :new }
            format.json { render json: @item.errors, status: :unprocessable_entity }
        end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    
    if logged_in?
      if @item.user_id == current_user.id
        if @item.update(item_params)
          flash.now[:success] = "Item was successfully updated!"
          redirect_to action: "index"
        else
          respond_to do |format|
            format.html { render :edit }
            format.json { render json: @item.errors, status: :unprocessable_entity }
          end
        end
      else
        flash.now[:danger] = "This is not your item, it was not updated!"
        respond_to do |format|
            format.html { render :edit }
            format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:danger] = "You are not logged in, login to update an item that is yours!"
        respond_to do |format|
            format.html { render :edit }
            format.json { render json: @item.errors, status: :unprocessable_entity }
        end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.permit(:user_id, :serial_no, :name, :tag, :location, :price, :brand, :model, :description, :status, images: [])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
    
    def checked_in(item)
        
        status = true
        
        if item.rentals.count > 0
            item.rentals.each do |rental|
                if !rental.buyer_checkin_confirm || !rental.seller_checkin_confirm
                    status = false
                end
            end
        end
        
        status
    end
    
    def current_rental(item)
        
        current_rental = false
    
        if item.rentals.count > 0
            item.rentals.each do |rental|
                if !rental.buyer_checkin_confirm || !rental.seller_checkin_confirm
                    current_rental = rental
                end
            end
        end
        
        if current_rental
            current_rental.id
        else
            current_rental
        end
        
    end
    
    def pending(item)
        
        pending = false
        
        if item.rentals.count > 0
            item.rentals.each do |rental|
                if !rental.approval
                    pending = true
                end
            end
        end
        
        pending
    end 
    
    def buyer_rented(item)
        
        button = false
        
        if item.rentals.count > 0
            item.rentals.each do |rental|
               if rental.user_id == current_user.id && (!rental.buyer_checkin_confirm || !rental.seller_checkin_confirm)
                   puts "CONFIRM"
                   button = true
               end
            end
        end
        
        button
        
    end
    
    def seller_rented(item)
        
        button = false
        
        if item.rentals.count > 0
            item.rentals.each do |rental|
               if rental.item.user_id == current_user.id && (!rental.seller_checkin_confirm || !rental.buyer_checkin_confirm)
                   button = true
               end
            end
        end
        
        button
        
    end
    
    def buyer_checked_in(item)
        
        button = false
        
        if item.rentals.count > 0
            item.rentals.each do |rental|
               if rental.user_id == current_user.id && rental.buyer_checkin_confirm && !rental.seller_checkin_confirm
                   button = true
               end
            end
        end
        
        button
        
    end
    
    def seller_checked_in(item)
        
        button = false
        
        if item.rentals.count > 0
            item.rentals.each do |rental|
               if rental.item.user_id == current_user.id && rental.seller_checkin_confirm && !rental.buyer_checkin_confirm
                   button = true
               end
            end
        end
        
        button
        
    end
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :serial_no %>
    <%= form.text_field :serial_no %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="group-form row">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>
  
  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_form_modal.html.erb
<%= form_with url: items_path do |form| %>

<div class="form-group row">
    <%= form.label "Name:", :class => "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :name, :class => "form-control", :required => true %>
    </div>
</div>
<div class="form-group row">
    <%= form.label "Description:", :class => "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :description, :class => "form-control", :required => true %>
    </div>
</div>
<div class="form-group row">
    <%= form.label "Serial #:", :class => "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :serial_no, :class => "form-control", :required => true %>
    </div>
</div>
<div class="form-group row">
    <%= form.label "Tags:", :class => "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :tag, :class => "form-control", :required => true %>
    </div>
</div>
<div class="form-group row">
    <%= form.label "Price:", :class => "col-2 col-form-label" %>
    <div class="col-10">
      <input name="price" class="form-control" pattern="^[0-9]*\.[0-9]{2}$" required />
    </div>
</div>
<div class="form-group row">
    <%= form.label "Brand:", :class => "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :brand, :class => "form-control", :required => true %>
    </div>
</div>
<div class="form-group row">
    <%= form.label "Model:", :class => "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :model, :class => "form-control", :required => true %>
    </div>
</div>
<div class="form-group row">
    <%= form.label "Images:", :class => "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.file_field :images, multiple: true, :required => true %>
    </div>
</div>
<div class="actions">
    <%= form.submit "Post Item", :class => "btn btn-info post-item-btn" %>
</div>
<% end %>

app/views/items/_item_card.html.erb
  <div class="col-md-3">
    <%= link_to :controller => :items, :action => 'show', :id => item.id do %>
    <div class="card mb-3 shadow-sm">
      <% if item.images.count > 0 %>
        <% if item.images[0].variable? %>
          <%= image_tag item.images[0], class: "card-img-top item-image-card" %>
        <% elsif item.images[0].previewable? %>
          <%= image_tag item.images[0], class: "card-img-top item-image-card" %>
        <% end %>
      <% elsif item.image_url %>
        <%= image_tag(item.image_url, class: "card-img-top") %>
      <% else %>
        <%= image_tag("items/placeholder.svg", class: "card-img-top") %>
      <% end %>
      <div class="card-body">
        <h4><%= truncate(item.name, :length => 15) %></h4>
        <h4 class="text-info"><strong><%= number_to_currency(item.price) %></strong></h4>
        <span class="card-info text-muted"><%= item.user.city %>, <%= item.user.state %>
          <% if pending(item) %>
            <span class="badge badge-info item-status-badge">Pending</span>
          <% elsif !checked_in(item) %>
            <span class="badge badge-info item-status-badge">Out</span>
          <% end %>
          
        </span>
        
        
      </div>
      <% end %>
      
      <% if current_user %>
        <% if !checked_in(item) && !pending(item) %>
          <% if buyer_rented(item) %>
            <div class="card-footer">
              <% if !buyer_checked_in(item) %>
                <%= button_to rentals_buyer_checkin_confirm_path(:rental_id => current_rental(item)), remote: true, :class => "btn btn-info btn-block", method: :post do %>
                    Buyer Check-in
                <% end %>
              <% else %>
                <button class="btn btn-info btn-block" disabled>Awaiting Seller Check-in</button>
              <% end %>
            </div>
          <% elsif seller_rented(item) %>
            
            <div class="card-footer">
              <% if !seller_checked_in(item) %>
                <%= button_to rentals_seller_checkin_confirm_path(:rental_id => current_rental(item)), remote: true, :class => "btn btn-info btn-block", method: :post do %>
                    Seller Check-in
                <% end %>
              <% else %>
                <button class="btn btn-info btn-block" disabled>Awaiting Buyer Check-in</button>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    
  </div>

app/views/items/_item_info.html.erb
  <% if checked_in(@item)
      @disabled = ""
      @rent_btn_text = "Rent"
    else
      @disabled = "disabled"
      @rent_btn_text = "Unavailable"
  end %>
  
  <div class="container bg-light">
    <div class="row spacer-20 bg-light"></div>
    <div class="row">
      <div class="col-7 bg-light">
        <div class="row">
          <div class="col">
            <span class="item-name"><%= item.name %></span>
            <span class="item-price text-info">(<%= number_to_currency(item.price) %>/day)</span>
          </div>
        </div>
        <div class="row">
          <span class="ml-3"><strong>Location: </strong>&nbsp<%= item.user.city %>, <%= item.user.state %> &nbsp<%= fa_icon("map-marker") %>&nbsp Local pickup ( <%= number_with_precision(@distance, :precision => 1) %> miles away)</span>
        </div>
        <hr>
        <div class="row">
          <span class="ml-3 mr-2">
            <%= item.description %> 
          </span>
        </div>
        <hr>
        <div class="row">
          <div class="tag-container ml-2">
            <button type="button" class="btn btn-outline-info item-option ml-2"><%= fa_icon("bookmark") %> Bookmark</button>
            <button type="button" class="btn btn-outline-info item-option ml-2"><%= fa_icon("share-square-o") %> Share</button>
            <button type="button" class="btn btn-outline-info item-option ml-2"><%= fa_icon("flag") %> Report</button>
          </div>
        </div>
        
        <div class="row mt-3">
          <div class="tag-container ml-2">
            <% @tags.each do |tag| %>
              <button type="button" class="btn btn-info ml-2"><%= tag %></button>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-5 bg-light">
        <div class="row mt-2 mb-2">
          <div class="col-5">
            <%= image_tag("default_avatar.jpg", :class => "profile-picture-item float-right d-block") %>
          </div>
          <div class="col-7 mt-2">
            <%= link_to :controller => :users, :action => 'show', :id => item.user.id do %>
            <span class="profile-user-name"><%= item.user.fname %> <%= item.user.lname %></span>
            <% end %>
            </br>
              <%= render 'users/flat_rating', rating: @rating %>
              (<%= @rating_count %>)</br>
          </div>
        </div>
        <div class="row">
          <div class="item-option-container ml-auto mr-auto">
            <% if checked_in(@item) %>
              <button type="button" data-target="#RentModal" data-toggle="modal" class="btn btn-info item-option ml-2"><%= fa_icon('exchange') %>  Rent</button>
            <% else %>
              <button type="button" class="btn btn-info item-option ml-2 disabled"><%= fa_icon('exchange') %>  Unavailable</button>
            <% end %>
            <button type="button" class="btn btn-info item-option ml-2"><%= fa_icon('comment') %>  Contact</button>
            <button type="button" class="btn btn-info item-option ml-2"><%= fa_icon('bookmark') %>  Bookmark</button>
          </div>
        </div>
        <div class="row mt-3">
          <%= image_tag("http://maps.googleapis.com/maps/api/staticmap?center=#{item.user.latitude},#{item.user.longitude}&zoom=15&size=450x200&key=AIzaSyA_x25mqDphJPz0jrC21MWQCICDKqxTCL8", :class => "mx-auto d-block profile-map") %>
        </div> 
      </div>
    </div>
    
    <div class="modal fade bd-example-modal-lg" id = "RentModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Rent Item</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="alert alert-info" role="alert">
            Fill out the form below to submit a rent request for the item to the user.  Once submitted it will go into a pending status until approved by the user.
          </div>
          <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>
          <%= render 'items/rent_modal', rental: @rental, item: @item %>
      </div>
    </div>
  </div>
</div>

app/views/items/_rent_modal.html.erb
<%= form_with model: rental, url: rentals_path(item_id: @item.id), :remote => true do |form| %>

<div class="form-group row">
    <%= form.label "Rental Start Date:", :class => "col-4 col-form-label" %>
    <div class="col-8">
      <%= form.date_select :rental_start_date, :order => [ :month, :day, :year ], :use_two_digit_numbers => true, :class => "form-control" %>
    </div>
</div>
<div class="form-group row">
    <%= form.label "Rental End Date:", :class => "col-4 col-form-label" %>
    <div class="col-8">
      <%= form.date_select :rental_end_date, :order => [ :month, :day, :year ], :use_two_digit_numbers => true, :class => "form-control" %>
    </div>
</div>
<div class="form-group row">
    <%= form.label "$/Day", :class => "col-4 col-form-label" %>
    <div class="col-8">
      $<span id="price-per-day"><%= @item.price %></span>
    </div>
</div>
<div class="form-group row">
  <%= form.label "Total Price:", :class => "col-4 col-form-label" %>
  <div class="col-8">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">$</span>
        </div>
        <input type="text" class="form-control" id="total-price" value="<%= @item.price %>" aria-label="Amount (to the nearest dollar)">
      </div>
  </div>
</div>
<div class="form-group row">
    <%= form.label "Need Assistance?:", :class => "col-4 col-form-label" %>
    <div class="col-1">
      <%= form.check_box :assistance, :class => "form-control" %>
    </div>
    <div class="col-7">
      <select class="form-control" id="assistance_reason" name="assistance_reason">
        <option value="">Select reason for assistance</option>
        <option value="Setup">Setup</option>
        <option value="Usage">Usage</option>
      </select>
    </div>
</div>
<div class="form-group row">
    <%= form.label "Comment:", :class => "col-4 col-form-label" %>
    <div class="col-8">
      <%= form.text_area :comment, :class => "form-control" %>
    </div>
</div>
<div class="actions">
    <%= form.submit "Rent Item", :class => "btn btn-info post-item-btn" %>
</div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <%= stylesheet_link_tag "home", media: "all" %>

    <title>Album example for Bootstrap</title>

  </head>

  <body>

<%= render 'home/navbar' %>

    <main role="main">
      <div class="p-3 p-md-5 text-white bg-info nav-buffer">
    
      </div>

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">eRent</h1>
          <p class="lead text-muted">A peer-2-peer rental app to allow users to make some extra cash on the side renting out items they no longer use.</p>
        </div>
      </section>
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <p id="error"><%= flash[:error] %></p>

      <div class="album py-5 bg-light">
        <div class="container">

          <% if @items.count > 0 %>
            <div class="card-columns">
              <% @items.each do |item| %>
                <% puts item %>
                <%= render 'home/item_card', item: item %>
              <% end %>
  
            </div>
          <% else %>
            <div class="alert alert-info" role="alert">
              No items matched your search results.
            </div>
          <% end %>
        </div>
      </div>

    </main>

<%= render 'home/footer' %>

  </body>
</html>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<%= stylesheet_link_tag "items", media: "all" %>

<%= render 'home/navbar' %>


  <div class="p-3 p-md-5 text-white  bg-info nav-buffer">
    
  </div>
  
  <div class="p-3 p-md-5 text-white bg-dark item-image-jumbotron">
    <% if @item.images.count > 0 %>
        <% if @item.images[0].variable? %>
          <%= image_tag @item.images[0], class: "item-image mx-auto d-block big-item-image" %>
        <% elsif @item.images[0].previewable? %>
          <%= image_tag @item.images[0], class: "item-image mx-auto d-block big-item-image" %>
        <% end %>
      <% elsif @item.image_url %>
        <%= image_tag(@item.image_url, class: "item-image mx-auto d-block big-item-image") %>
      <% else %>
        <%= image_tag("items/placeholder.svg", class: "item-image mx-auto d-block big-item-image") %>
      <% end %>
  </div>
  <div class="album py-5 bg-light">
  <%= render 'item_info', item: @item, tags: @tags %>
    <hr>
    <% if @similar_items.count > 0 %>
    <div class="row mt-3">
      <span class="item-name ml-3">Similar Items</span></br>
    </div>
    
      <div class="card-group mt-3">
        <% @similar_items.limit(4).each do |item| %>
          <%= render 'item_card', item: item %>
        <% end %>
      </div>
    <% end %>
    
    <% if @item.user.items.where.not(id: @item.id).count > 0 %>
    <div class="row mt-3">
      <span class="item-name ml-3"><%= @item.user.fname %>'s Other Items</span></br>
    </div>
    
    <div class="card-group mt-3">
      
      <% @user_other_items.limit(4).each do |item| %>
        <%= render 'item_card', item: item %>
      <% end %>
    </div> 
    <% end %>
    <div class="row spacer-20 bg-light"></div>
  </div>
</div>
<%= render 'home/footer' %>